[package]
name = "morseclock"
version = "0.1.0"
authors = ["Maik Allgöwer <maik@llgoewer.de>"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "morseclock-cli"
path = "bin/cli.rs"

[dependencies]
chrono = "*"